#!/usr/bin/env bash
#
# git-commit-msg-linter@5.0.7 06/05/2024, 20:25:48
# id=commit-msg-linter - THE id COMMENT SHOULD NOT BE DELETED OR MODIFIED!
# It's used to check whether this commit-msg hook file is created by us,
# if it is then we can remove it confidently on uninstallation.

cat C:/Sistemas/ReactJS/fullstackweek-foods/node_modules/commit-msg-linter/commit-msg-linter.js | node --input-type=commonjs
